"""Add projects and parsed resume data

Revision ID: 63edca3bfb16
Revises: 6a0aed15fcd6
Create Date: 2026-02-24 04:41:55.802566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63edca3bfb16'
down_revision: Union[str, Sequence[str], None] = '6a0aed15fcd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('seeker_profile_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['seeker_profile_id'], ['seeker_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_seeker_profile_id'), 'projects', ['seeker_profile_id'], unique=False)
    op.add_column('seeker_profiles', sa.Column('parsed_resume_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seeker_profiles', 'parsed_resume_data')
    op.drop_index(op.f('ix_projects_seeker_profile_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
